# Generated by Django 2.0.1 on 2018-01-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0003_item_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
